### ISSUE TITLE
Tilda behaviour with "Auto hide delay" 0 value

### ISSUE THREAD

**Issue by toniwiki** [tsloughter/tilda#10]
I use the Tilda option from preferences "Hide when tilda loses focus" with "Auto hide delay" = 0. With this value, shouldn't Tilda hide so quickly when loses focus as i press pull down shortcut for example ? It has a delay even with 0 value.

Is this a bug or normal behaviour?

**Comment by lanoxx** [comment]
I just took a quick look at the code. It looks like currently a timer is always registered even if the timeout is 0, I think it could be made faster if we only register timers for delays greater than 0.

**Comment by lanoxx** [comment]
I have fixed the issue in the lanoxx/master branch. Now the window is pulled up directly if the value is zero and it sleeps if the value is between 1 and 1000ms, only if its greater, then a timer is registered.

**Comment by toniwiki** [comment]
Great! Thank you
