### ISSUE TITLE
Custom keyboard shortcuts

### ISSUE THREAD

**Issue by fteem** [tsloughter/tilda#13]
Hello.

First, thank you for creating an awesome terminal emulator! I really enjoy using it.
What I was wondering is is it possible to add custom keyboard shortcuts? 

For example I find Ctrl-H and Ctrl-L more natural for switching between tabs instead of using Ctrl - Page Up/Down. Is this possible?
If it is not, I would really love to see this feature in tilda because I think it will boost peoples productivity even more.

Thanks.

**Comment by ntrp** [comment]
You can use this fork of tsloughter tilda which is written for gtk3 and includes customizable shortcuts from the options interface:

https://github.com/lanoxx/tilda

**Comment by fteem** [comment]
Thank you for the quick answer!

**Comment by lanoxx** [comment]
Hi fteem, 

Go to know you like it. Please let me know if the gtk+3 works well for you and feel free to report bugs for it if you encounter any. 

I am currently trying to get tilda into debian and arch linux so that it will appear in future distributions. But it seems to be not so easy.

**Comment by fteem** [comment]
Hello lanoxx

Although I had some problems with the installation on Ubuntu (had to install tons of packages), I like it and it is working okay. Getting tilda into deb/arch would be real nice because that will simplify the installation process a lot. 
Regarding bugs, I haven't noticed any yet. One thing that I bothers me is the white-ish border that appears when two or more tabs are created, but I wouldn't call it a bug. It's just personal preference I guess.

**Comment by lanoxx** [comment]
Hi,

The border thing is a known thing which is easily fixable. Take a look at https://github.com/tsloughter/tilda/issues/7 for the detailed discussion. The TL;DR is that you can put a style.css into tildas config folder and deactivate the border. This is rather a problem of the system theme than of tilda. The default gnome theme adwaita does not have this issue.

**Comment by fteem** [comment]
Yup, that fixes it. Thanks a lot!
