### ISSUE TITLE
tilda doesn't allow to vertically maximize its window

### ISSUE THREAD

**Issue by x1o** [tsloughter/tilda#15]
I'm using tilda 0.09.6 on Ubuntu 13.04 (0.09.6-2ubuntu1 to be precise) with Unity UI and I experience something which consider a bug: tilda doesn't allow resizing its window so that it is fully maximized vertically, i.e. there's always a gap between the lower edge of the screen and tilda's window (no matter which geometry / position I set).

I think this behaviour might be intentional and is in fact desirable in a DE where the user has a taskbar in the lower part of the screen, but is a little annoying in some other cases (say, in Unity with the default configuration).

**Comment by tsloughter** [comment]
I haven't tested on Unity, and actually don't use or work on tilda anymore. Sorry I didn't point you to https://github.com/lanoxx/tilda earlier.

**Comment by x1o** [comment]
Tristan, for some reason I thought that you were the original author of tilda, while it seems to be [this guy](https://github.com/lanoxx). I opened the same ticket in his repo as well.

Anyway, thanks for your reply.

**Comment by lanoxx** [comment]
Tristan is the original author. However I took over development about a year ago. So if you have any issues please file them in my repo.

Regards
Lanoxx
