### ISSUE TITLE
Support for customized color rendering

### ISSUE THREAD

**Issue by rpdelaney** [tsloughter/tilda#9]
Over here is a pretty spiffy zenburn theme for a tty: http://phraktured.net/linux-console-colors.html

It looks really nice on my machine. But I noticed there's no way to customize the color rendering in tilda like so. It would be great if this were supported so users could customize their fonts and colors to match their own aesthetic.

**Comment by lanoxx** [comment]
Hi,
I'm not sure such a feature would need to go into Tilda. Tilda just loads any terminal of your choice, the default should be bash, but you can also load a python shell or zsh or anything else that give you a shell. The terminal it self is plugged in via libvte (which is a virtual terminal emulator), so your feature request probably needs to go there.
Of course, you can correct me if I'm wrong.
Regards
Lanoxx

**Comment by lanoxx** [comment]
Hi,

actually you can edit the colors in tilda, via the colors tab in the preferences. I have now added the color scheme you suggested to the default color schemes that are available. I guess it cant hurt to have a few more color schemes available. There is currently no way to load such colors from a configuration file, but if you want to provide a patch I will be happy to merge it.

You can try out the color scheme from my branch: lanoxx/tilda

Regards
Lanoxx
